DROP TABLE IF EXISTS [dbo].[RPTCHILD];
DROP TABLE IF EXISTS [dbo].[RPTPARENT];
CREATE TABLE [dbo].[RPTCHILD](
    [pghNr] [int] IDENTITY(1,1) NOT NULL,
    [rptNr] [int] NOT NULL,
    [pghName] [varchar](50) NOT NULL
    ) ON [PRIMARY];
CREATE TABLE [dbo].[RPTPARENT](
    [rptNr] [int] IDENTITY(1,1) NOT NULL,
    [rptName] [varchar](50) NOT NULL,
    CONSTRAINT [PK_RPTNR] PRIMARY KEY CLUSTERED
(
[rptNr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];
ALTER TABLE [dbo].[RPTCHILD]  WITH CHECK ADD  CONSTRAINT [FK_RPTPARENT] FOREIGN KEY([rptNr])
    REFERENCES [dbo].[RPTPARENT] ([rptNr])
    ON DELETE CASCADE;
